version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never

  php73:
    image: php:7.3-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: "serverName=application"